FROM python:3.8-buster

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir /app
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY requirements-dev.txt .
RUN pip install -r requirements-dev.txt

ARG MAPIT_KEY
ARG MAPIT_GENERATION=41
ARG ACCESS_KEY

ENV MAPIT_KEY=$MAPIT_KEY ACCESS_KEY=$ACCESS_KEY MAPIT_GENERATION=$mapit_generation
